-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 16-Abr-2020 às 05:19
-- Versão do servidor: 10.2.31-MariaDB
-- versão do PHP: 7.2.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `u139808959_sistema_dados`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `alunos`
--

CREATE TABLE `alunos` (
  `idAluno` int(11) NOT NULL,
  `nomeAluno` varchar(100) DEFAULT NULL,
  `contAcertadas` int(3) DEFAULT NULL,
  `contErradas` int(3) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `disciplinas`
--

CREATE TABLE `disciplinas` (
  `idDisciplina` int(11) NOT NULL,
  `nomeDisciplina` varchar(50) NOT NULL,
  `professor` varchar(100) DEFAULT NULL,
  `dataInicio` datetime DEFAULT NULL,
  `dataTermino` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `disciplinas`
--

INSERT INTO `disciplinas` (`idDisciplina`, `nomeDisciplina`, `professor`, `dataInicio`, `dataTermino`) VALUES
(1, 'Logica Computacional', 'Adriane Aparecida Loper', '2020-02-17 00:00:00', '2020-03-23 00:00:00'),
(2, 'Modelagem de Dados', 'Gilberto Fernandes Junior', '2020-02-17 00:00:00', '2020-05-30 00:00:00'),
(3, 'Analise e Modelagem de Sistemas', 'Iolanda Claudia Sanches Catarino', '2020-03-21 00:00:00', '2020-06-13 00:00:00'),
(4, 'Algoritmos e Programação Estruturada', 'Vanessa Matias Leite', '2020-04-18 00:00:00', '2020-06-13 00:00:00');

-- --------------------------------------------------------

--
-- Estrutura da tabela `perguntas`
--

CREATE TABLE `perguntas` (
  `idPergunta` int(11) NOT NULL,
  `uniEstudo` enum('1','2','3','4') DEFAULT NULL,
  `fonte` enum('av','aap','adg','livro') DEFAULT NULL,
  `perguntas` mediumtext NOT NULL,
  `respostaA` longtext NOT NULL,
  `respostaB` longtext NOT NULL,
  `respostaC` longtext NOT NULL,
  `respostaD` longtext NOT NULL,
  `respostaE` longtext NOT NULL,
  `respostaCorreta` enum('A','B','C','D','E') NOT NULL,
  `idDisciplina` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `perguntas`
--

INSERT INTO `perguntas` (`idPergunta`, `uniEstudo`, `fonte`, `perguntas`, `respostaA`, `respostaB`, `respostaC`, `respostaD`, `respostaE`, `respostaCorreta`, `idDisciplina`) VALUES
(1, '1', 'aap', 'Hoje em dia, com sistemas informacionais espalhados por todos os setores da economia e em nosso dia-a-dia, uma das escolhas mais populares na hora de decidir qual a profissão seguir são, com certeza, profissões relacionadas à computação, programação ou análise de sistemas. Para ser um profissional dessa área e ter condições de progredir na profissão que demanda construção de sistemas que envolvem software, será necessário um conhecimento sólido de lógica computacional. A lógica formal começa nos estudos de Aristóteles, na Grécia Antiga.</br>\r\n\r\nA lógica é dita formal quando', 'Analisa e representa a forma de qualquer argumento para que possa ser considerado válido para se chegar a uma conclusão, em que se pode inferir alguma resposta.\r\n', 'Permite expressar as premissas e suas relações por meio de símbolos matemáticos, construindo equações para expressar argumentos.', 'Nosso conhecimento, o conhecimento humano, parte de duas fontes principais. A primeira trata da receptividade das impressões através de nossos sentidos.', 'É relativa à faculdade de conhecer um objeto por representações mentais, através do pensamento.', 'Está relacionado ao que é obtido através de nossos sentidos, à observação, à experimentação, com base na presença real de determinado objeto.', 'A', 1),
(2, '1', 'aap', 'O estudo da lógica permite, que de forma prática, possamos entender como nosso raciocínio é formado, fundamentar nossos argumentos, escrever e registrar de forma organizada, nos comunicarmos melhor, além de fazer conexões entre diversos assuntos e entender melhor o mundo que está a nossa volta.</p><p>De acordo com as informações apresentadas na tabela a seguir, faça a associação das nomenclaturas de alguns termos importantes e muito utilizados na lógica com suas respectivos definições.</p>\r\n<table><tr><td>I. Conhecimento Empírico</td><td>1. Se preocupa com argumentos que permitam chegar a conclusões gerais a partir de casos particulares.</td></tr><tr><td>II. Conhecimento Puro</td><td>2. É aquela que parte de premissas, afirmativas ou leis mais gerais, permitindo a obtenção de verdades menos gerais, ou particulares.</td></tr><tr><td>III. Lógica Dedutiva</td><td>3. é relativo à representação que não se mescla com a sensação, é puramente racional.</td></tr><tr><td>IV. Lógica Indutiva</td><td>4. Está relacionado ao que é obtido através de nossos sentidos, à observação, à experimentação, com base na presença real de determinado objeto.</td></tr></table>\r\n\r\n<p>Assinale a alternativa que apresenta a associação correta entre as colunas:', 'I - 4; II - 3; III - 1; IV - 2.', 'I - 4; II - 3; III - 2; IV - 1.', 'I - 4; II - 2; III - 3; IV - 1.', 'I - 3; II - 4; III - 2; IV - 1.', 'I - 3; II - 1; III - 4; IV - 2.', 'B', 1),
(3, '1', 'aap', 'A Lógica atualmente é fortemente estudada em matérias relacionadas a ciência da computação, tecnologia da informação e programação, pois é a base para a construção de algoritmos. É importante ter um forte entendimento desta ciência para que possamos compreender como construir algoritmos e desenvolver e analisar sistemas computacionais.</p><p>Veja um exemplo de conclusão lógica:</p><p>Bruce é uma pessoa e sabe caminhar.</br>Klark é uma pessoa e sabe caminhar.</br>Diana é uma pessoa e sabe caminhar.</br>(...)</br>Portanto, toda pessoa sabe caminhar.</p><p>O exemplo de conclusão lógica descrita acima foi obtido através:', 'Do Conhecimento Empírico.', 'Do Conhecimento Puro.', 'Da Lógica Indutiva.', 'Da Lógica Transcendental.', 'Da Lógica Simbólica.', 'C', 1),
(4, '1', 'aap', 'Em um sentido amplo, a lógica é o estudo da estrutura e dos princípios relativos ao raciocínio, à estruturação do pensamento, com ênfase na argumentação, que pode ser considerada como válida ou inválida. Com base em premissas, ela permite a construção do raciocínio indutivo ou dedutivo, e também a realização de operações lógicas simbólicas e demonstrações matemáticas.</p><p>Podemos classificar o estudo da lógica em três grandes períodos:', 'O Período Aristotélico, o Período Booleano e o Período Atual.\r\n', 'O Período do Silogismo, o Período Booleano e o Período Isaacotélico', 'O Período Aristotélico, Período do Silogismo e o Período Atual.', 'O Período Aristotélico, o Período Booleano e o Período do Silogismo.', 'O Período Aristotélico, o Período Booleano e o Período Isaacotélico.', 'A', 1),
(5, '1', 'adg', 'A lógica de programação é um tipo de linguagem usada para programar no computador. Ela é fundamental no desenvolvimento de programas e sistemas de informática, já que dela surge um encadeamento lógico de desenvolvimento. Esse desenvolvimento acontece em função do algoritmo, que nada mais é que uma sequência lógica de instruções que faz com que a função seja executada.</p><p>Dentro desse contexto, preencha corretamente as lacunas.</p><p>A lógica está relacionada a __________, pois é a base para a construção e desenvolvimento de __________ e para a __________.</p><p>Assinale a alternativa que completa corretamente as lacunas:', 'Ciências da Computação, Tecnologia da Informação e programação / algoritmos / análise de sistemas.\r\n\r\n', 'Matemática e Ciências / raciocínios / criação de problemas.', 'Ciências da Computação e informática / Matemática / análise de sistemas.', 'Tecnologia de Informação e programação / relatórios / atividades racionais.', 'Matemática / argumentos / construção de falácias.', 'A', 1),
(6, '1', 'adg', 'No entendimento de lógica, alguns termos são muito utilizados e devem ser conhecidos para facilitar o raciocínio. A tabela 1, a seguir, apresenta alguns destes termos e suas definições:</p><p>Tabela 1 – Termos lógicos</p>\r\n<table><tr><td>Termos</td><td>Definição</td></tr><tr><td>1.Proposição</td><td>A – Possibilita a dedução de uma conclusão a partir das premissas.</td></tr><tr><td>2.Premissa</td><td>B – Conjunto de enunciados que se relacionam uns com os outros.</td></tr><tr><td>3.Argumento</td><td>C – Frase declarativa.</td></tr><tr><td>4.Silogismo</td><td>D – Argumentos incorretos.</td></tr><tr><td>5.Falácia</td><td>E – Proposições para um raciocínio.</td></tr></table><p>Analise a tabela 1 e assinale a alternativa que contém a associação correta entre as colunas:', '1-A / 2-E / 3-B / 4-D / 5-C.', '1-C / 2-E / 3-B / 4-A / 5-D.', '1-C / 2-B / 3-A / 4-E / 5-D.', '1-A / 2-C / 3-E / 4-D / 5-B.', '1-E / 2-D / 3-C / 4-B / 5-A.', 'B', 1),
(7, '1', 'adg', 'A lógica utiliza argumentos para que seja possível desenvolver um raciocínio. Seguindo algumas regras e um raciocínio correto, a probabilidade de se alcançar conclusões verdadeiras é muito grande. Nesse sentido, observe a figura 1, a seguir:</p><p>Figura 1 – Atividades dos corretores</p><img src=\'../../img/logica-tarefas.jpg\'><p>Fonte: elaborada pelo autor.</p><p>Analisando a figura 1, assinale a alternativa que apresenta a afirmação correta:', 'O corretor 1 elabora, digita e fecha contratos do corretor 2.', 'O corretor 2 elabora, digita e fecha contratos do corretor 1.', 'Elaborar, digitar e fechar contrato são atividades dos dois corretores.', 'O corretor 1 elabora, digita e fecha contratos de venda de imóveis.', 'O corretor 2 elabora, digita e fecha contratos de compra de imóveis.', 'C', 1),
(8, '1', 'adg', 'O argumento lógico é deduzido a partir daquilo que é colocado como verdade, e a nossa opinião sobre a validade das premissas não pode interferir na elaboração da conclusão.</p><p>Considere as premissas:</p><p>A) Todo número par é escrito na forma 2n, onde n é um número natural.</br>B) O número 5 é escrito como 5 equals 2 times 2.</p><p>Assinale a alternativa que apresenta a conclusão segundo as premissas A e B.', '5 não é um número par.', 'Todo número par não é ímpar.', '5 é um número ímpar.', '5 é um número par.', 'Todo número ímpar é par.', 'D', 1),
(9, '1', 'aap', 'Uma visão pode ser um subconjunto de um banco de dados. Podem ser resultantes de pesquisas, que retornam parte das informações armazenadas. Um SGBD com suporte as múltiplas visões, deve proporcionar facilidades para a definição de diversas visões.</p><p>Uma visão (ou _______) pode ser considerada como uma ___________ ou uma _____________ armazenada. Permitem mais do que somente ______________ os dados, e também implementar algumas _________.</p><p>Com base na sentença, assinale a alternativa que apresenta as palavras que completam a frase corretamente.', 'função/tabela virtual/construir/visualizar/restrições.', 'view/tabela virtual/consultar/visualizar/restrições.', 'trigger/tabela básica/construir/explorar/restrições.', 'tabela/trigger básica/construir/explorar/restrições.', 'tabela virtual/consulta básica/explorar/construir/restrições.', 'B', 2),
(10, '2', 'aap', 'Um problema recorrente envolvendo subconjuntos diz respeito à determinação do número de subconjuntos de um determinado conjunto. Deste modo, há um teorema para contabilizar o número de subconjuntos de um conjunto qualquer, conhecendo-se a sua cardinalidade.</p><p>Seja A um conjunto com cardinalidade igual a 8. Quantos subconjuntos de A poderiam ser contabilizados?</p><p>Assinale a alternativa que apresenta o número correto de subconjuntos de A.', '1024', '2048', '1025', '256', '121', 'D', 1),
(11, '2', 'aap', 'Usualmente, um conjunto é descrito pelas suas propriedades. Por exemplo, se o conjunto é de números pares positivos, ao invés de escrever <img class=\'imgpq\' src=\'../../img/perg-aap22a.png\'> podemos representar esse conjunto como <img class=\'imgpq\' src=\'../../img/perg-aap22b.png\'>.<p></p>Assinale a alternativa que apresenta o conjunto definido por<img class=\'imgpq\' src=\'../../img/perg-aap22c.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap22aa.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap22bb.png\' >', '<img class=\'imgpq\' src=\'../../img/perg-aap22cc.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap22dd.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap22ee.png\'>', 'E', 1),
(12, '2', 'aap', 'Na teoria dos conjuntos, há notações específicas para denotar a relação entre dois conjuntos. Para que qualquer pessoa tenha um entendimento correto, é necessário ter o domínio do uso das notações.</p><p>Considere os conjuntos <img class=\'imgpq\' src=\'../../img/perg-aap23a.png\'> e <img class=\'imgpq\' src=\'../../img/perg-aap23b.png\'>. Pode-se verificar que M e N possuem uma relação entre si.</p><p>Assinale a alternativa que apresenta a relação existente entre M e N.', '<img class=\'imgpq\' src=\'../../img/perg-aap23aa.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap23bb.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap23cc.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap23dd.png\'>', '<img class=\'imgpq\' src=\'../../img/perg-aap23ee.png\'>', 'C', 1),
(13, '2', 'aap', 'Mesmo não conhecendo quais são os elementos dos conjuntos, se souber a cardinalidade da união, interseção ou de um conjunto, pode-se calcular a cardinalidade deo conjunto desconhecido.</p><p>Considere o seguinte: Sejam os conjuntos A e B tal que |A| = 20, |A n B| = 12 e |A ∪ B| = 60.</p><p>Assinale a alternativa com o valor correto de |B|.', '43', '52', '34', '79', '12', 'B', 1),
(14, '2', 'adg', 'Conjuntos podem ser definidos como coleções não-ordenadas de objetos que podem ser, de alguma forma, relacionados (FERREIRA, 2001).</p><p>Com base na teoria dos conjuntos, analise o excerto a seguir, completando suas lacunas.</p><p>Um conjunto é chamado de finito quando sua ____________ é um número ____________. Caso contrário, é chamado de infinito. Um conjunto é chamado de conjunto ____________ quando sua cardinalidade é igual a zero, ou seja, é um conjunto desprovido de elementos.</p><p>Assinale a alternativa que preenche corretamente as lacunas.', 'Cardinalidade / inteiro / vazio', 'Ordem / real / inteiro', 'Ordem / inteiro / simbólico', 'Cardinalidade / natural / interno', 'Ordem / natural / vazio', 'A', 1),
(15, '2', 'adg', 'Conjuntos podem ser definidos como coleções não-ordenadas de objetos que podem ser, de alguma forma, relacionados. Com base nas propriedades básicas da teoria dos conjuntos, analise as afirmativas a seguir.</p><p>I. Geralmente utiliza-se letras maiúsculas do nosso alfabeto para representar os conjuntos.</br>II. Um objeto pertencente a um conjunto é chamado de elemento do conjunto. A relação de pertinência é indicada pelo símbolo subset of.</br>\r\nIII. Cardinalidade do conjunto é o termo utilizado para representar o número de elementos do conjunto.</p><p>Considerando o contexto apresentado, é correto o que se afirma em:', 'I, apenas.', 'I e II, apenas.', 'I e III, apenas.', 'II e III, apenas.', 'I, II e III.', 'E', 1),
(16, '2', 'adg', 'Para descrevermos determinado conjunto, é necessário identificar seus elementos. Para tanto, pode-se proceder de algumas maneiras distintas. Sendo assim, analise as afirmativas a seguir e identifique quais são opções válidas para a identificação de elementos de um conjunto.</p><p>I. Listando todos os elementos do conjunto.</br>II. Indicando os primeiros elementos do conjunto.</br>III. Escrevendo uma propriedade que caracterize os elementos que constituem o conjunto.</p><p>Considerando o contexto apresentado, é correto o que se afirma em:\r\n\r\n', 'I, apenas.', 'I e II, apenas.', 'I e III, apenas.', 'II e III, apenas.', 'I, II e III.', 'C', 1),
(17, '2', 'adg', 'Os diagramas de Venn podem ser utilizados para ilustrar as operações binárias de conjuntos. Considere as figuras a seguir.</p><p><img class=\'\' src=\'\'></p><p>Assinale a alternativa que representa as regiões sombreadas das figuras (a) e (b), respectivamente.', 'A ∩ B ; A υ B.', 'A υ B ; A ∩ B.', 'A ⊆ B ; A ∩ B', 'A ⊆ B ; A ∪ B.', 'A ∩ B ; A ⊆ B.', 'C', 1),
(18, '3', 'aap', 'Proposição é uma sentença declarativa que pode ser classificada como verdadeira ou falsa, jamais ambas ao mesmo tempo. Ou seja, não pode haver dúvida quanto à classificação da sentença. Também podemos dizer que trata-se de uma classificação binária, pois só existem dois resultados possíveis: V ou F, ou ainda 1 ou 0.</p><p>Uma premissa é um ponto ou ideia de que se parte para armar um raciocínio.</p><p>Exemplo de Premissas:</p><p>- Maria é inteligente.</br>- Maria não estudar muito.</br>- Todos os alunos inteligentes ou estudiosos são aprovados.</p><p>Com base no exemplo de Premissas acima e usando a Lógica Proposicional, podemos chegar a seguinte conclusão ...', 'Maria será aprovada.', 'Maria não será aprovada.', 'Maria é inteligente.', 'Maria é estudante.', 'Maria é inteligente sem estudar.', 'A', 1),
(19, '3', 'aap', 'No estudo da lógica, além de distinguir se uma frase é ou não um argumento, também é importante distinguirmos se uma sentença pode ou não ser classificada como verdadeira ou falsa (não ambas ao mesmo tempo).</p><p>Aponte qual frase não pode ser classificada (valorada) em verdadeira (V) ou falso (F):', 'O Paraguai é um pais da América Latina.', 'Mato Grosso é uma Cidade do Brasil.', 'São Paulo é a capital do Brasil.', 'Cinco mais um é igual a sete.', 'Que show!', 'E', 1),
(20, '3', 'aap', 'Proposição é uma sentença declarativa que pode ser classificada como verdadeira ou falsa, jamais ambas ao mesmo tempo. Ou seja, não pode haver dúvida quanto à classificação da sentença.</p><p>De acordo com as informações apresentadas na tabela a seguir, faça a associação dos três princípios básicos de uma proposição contidos na COLUNA A com seus respectivos significados contidos na COLUNA B.</p><table><tr><td>COLUNA A</td><td>COLUNA B</td></tr><tr><td>I. Princípio da Identidade</td><td>1. Toda proposição ou é verdadeira ou é falsa, não existindo um terceiro valor que ela possa assumir. Sendo P uma proposição tem-se: P ou não P.</td></tr><tr><td>II. Princípio da Não Contradição</td><td>2. Toda proposição é idêntica a si mesma. Ou seja, sendo P uma proposição: P é P</td></tr><tr><td>III. Princípio do Terceiro excluído</td><td>3. Uma proposição não pode ser verdadeira e falsa ao mesmo tempo. Sendo P uma proposição tem-se: não (P e não P).</td></tr></table><p>Assinale a alternativa que apresenta a associação correta entre as colunas:', 'I - 2, II - 3, III - 1.', 'I - 2, II - 1, III - 3.', 'I - 3, II - 2, III - 1.', 'I - 3, II - 1, III - 2.', 'I - 1, II - 2, III - 3.', 'A', 1),
(21, '3', 'aap', 'Uma proposição composta pode ser criada fazendo a conjunção de duas proposições simples, nesse caso, são utilizadas as palavras “e”, “mas”, “no entanto”, dentre outras para fazer a conexão. Também podemos criar uma proposição composta fazendo a disjunção de duas proposições simples, nesse caso, usamos a palavra “ou” para a conexão. A disjunção possui uma particularidade, ela pode ser inclusiva ou exclusiva.</p><p>Considere o contexto e avalie as seguintes proposições:</p><p>I. Rodrigo é estudante ou é trabalhador. Essa é uma proposição inclusiva.</br>II. Maria é Paulista ou é Carioca. Essa é uma proposição inclusiva.</br>III. Felipe é gordo ou é magro. Essa é uma proposição exclusiva.</br>IV. Arthur é baixo ou é alto. Essa é uma proposição exclusiva.</p><p>Agora, assinale a alternativa que apresenta a correta:', 'Apenas as afirmativas II, III e IV estão corretas.\r\n', 'Apenas as afirmativas I, III e IV estão corretas.', 'Apenas as afirmativas I, II e III estão corretas.', 'Apenas as afirmativas I, II e IV estão corretas.', 'As afirmativas I, II, III e IV estão corretas.', 'B', 1),
(22, '3', 'adg', 'Segundo Manzano(2019), na construção de algoritmos, os condicionais são amplamente utilizados. “Do ponto de vista computacional, uma condição é uma expressão booleana cujo resultado é um valor lógico falso ou verdadeiro\".</p><p>Uma expressão booleana como condição é conseguida a partir de', 'apenas proposições.', 'uma relação lógica entre dois elementos e um operador relacional.', 'apenas de proposições dedutivas.', 'conectivos lógicos e perguntas.', 'proposições booleanas.', 'B', 1),
(23, '3', 'adg', 'As proposições podem ser simples ou compostas. Ela será simples quando existir uma única afirmação na frase; e composta, quando existir, ao menos, duas proposições simples interligadas.</p><p>Nesse sentido, analise as afirmativas, a seguir:<br>I. Palavras usadas para separar proposições simples são chamados de conectivos lógicos.<br>II. São conectivos lógicos: <b>e, ou, não, se...então, se, e somente se</b>.<br>III. O conectivo lógico <b>e</b> é usado na operação lógica de disjunção.<br>IV. O conectivo lógico <b>ou</b> é representado pelo símbolo <b>v</b>.</p>É correto o que se afirma em:', 'I, apenas.', 'II e IV, apenas.', 'II, apenas.', 'I e III, apenas.', 'III e IV, apenas.', 'B', 1),
(24, '3', 'adg', 'Um argumento é elaborado através das proposições, buscando sempre uma conclusão que seja sustentada por uma ou mais premissas. Portanto, argumentar significa garantir uma conclusão verdadeira, baseada em premissas verdadeiras. Nesse sentido, analise a frase, a seguir:</p><p>Os carros fabricados no Brasil são taxados de impostos, que são caros. Logo, se o imposto é caro, os carros brasileiros também são.</p><p>Assinale a alternativa que contém a afirmação correta:', 'A frase é um argumento composto por duas premissas e duas conclusões.', 'A frase é um argumento composto por uma premissa e uma conclusão.', 'A frase é um argumento composto por duas premissas e uma conclusão.', 'A frase é um argumento composto por uma premissa e duas conclusões.', 'A frase não é um argumento.', 'C', 1),
(25, '3', 'adg', 'O cálculo proposicional ajuda a validar argumentos através da utilização de proposições. As proposições podem ser simples ou compostas. As proposições compostas são formadas por um encadeamento de proposições simples, unidas por conectivos lógicos. Na tabela 1, a seguir, são relacionados alguns conectivos e suas funções:</p><p>Tabela 1 – Conectivos lógicos</p><table><tr><td>Operador lógico</td><td>Definição</td><td>Conectivo de</td></tr><tr><td>A. Λ</td><td>1. Não</td><td>a. Disjunção</td></tr><tr><td>B. V</td><td>2. Se ... então</td><td>b. Bicondicional</td></tr><tr><td>C. ¬</td><td>3. E</td><td>c. Negação</td></tr><tr><td>D. →</td><td>4. Se, e somente se</td><td>d. Conjunção</td></tr><tr><td>E. ↔</td><td>5. Ou</td><td>e. Condicional</td></tr></table><p>Analisando a tabela 1, associe as colunas corretamente:Fonte: elaborada pelo autor', 'A-3-d / B-5-a / C-1-c / D-2-e / E-4-b.', 'A-1-c / B-3-e / C-5-b / D-2-a / E-4-d.', 'A-5-e / B-1-d / C-2-c / D-4-b / E-3-a.', 'A-4-d / B-2-c / C-5-a / D-3-e / E-1-b.', 'A-2-e / B-4-a / C-1-d / D-5-b / E-3-c.', 'A', 1),
(26, '1', 'aap', 'Conforme GUIMARÃES (2003), o conjunto de requisitos de um SGBD recebe o nome de ACID dos termos em inglês Atomicity, Consistency, Isolation, Durability ou respectivamenteAtomicidade, Consistência, Isolamento e Durabilidade. É fundamental verificar se o SGBD escolhido possui esses quatro fatores, no caso se o SGBD é ACID, para garantir que uma transação no banco de dados seja realizada com sucesso.</p><p>Analise as afirmativas relacionadas às propriedades ACID e ao controle transacional em um banco de dados:<p></p>I.A consistência, uma propriedade que deve ser garantida em um sistema de gerenciamento de banco de dados, ocorre em situações em que todas as ações de uma unidade de trabalho são efetivadas (commit) sem que haja falha na unidade de trabalho. Caso haja falha, é realizado roll back.<br>II.Transação é uma unidade atômica de processamento no banco de dados e tem a seguinte característica: ou estará terminada totalmente ou não foi realizada de forma alguma.<br>III.Isolamento é uma propriedade ligada à serialização de transações.<br>IV. A propriedade Atomicidade pode ser utilizada na serialização de transações em um banco de dados.<br>V. Atomicidade e Isolamento são duas propriedades que um banco de dados relacional deve respeitar.</p><p>Com relação às propriedades ACID, marque as alternativas corretas.\r\n\r\n', 'Apenas as afirmativas I e II estão corretas.', 'Apenas as afirmativas I e III estão corretas.', 'Apenas as afirmativas II e IV estão corretas.', 'Apenas as afirmativas II, III e V estão corretas.', 'Apenas as afirmativas I,II,IV e V estão corretas.', 'D', 2),
(27, '1', 'aap', 'Os Sistemas Gerenciadores de Banco de Dados evoluíram muito nessas últimas três décadas.Vários SGBD’s foram desenvolvidos por diversas empresas ao longo das última décadas, vários ainda estão no mercado e muitos ficaram obsoletos. Segundo KORTH et al (2012), os primeiros bancos de dados foram desenvolvidos a partir do sistema de arquivos e eram programados manualmente.</p><p>Avalie quais das seguintes alternativas são verdadeiras ou falsas, com relação à classificação dos bancos de dados:</p><p>( ).Banco de dados relacional;<br>( ).Banco de dados relacional/objetos;<br>( ).Banco de dados orientado a eventos;<br>( ).Banco de dados para Web com XML;<br>( ).Banco de dados para nuvem.</p><p>Marque a alternativa que corresponda a resposta correta na analise da classificação dos bancos de dados.', 'V - V - V - F - F.', 'V - F - V - F - F.', 'V - V - F - V - V.', 'F - V - F - V - V.', 'F - V - F - F - V.', 'C', 2),
(28, '1', 'aap', 'Na Modelagem Relacional, o conceito principal vem da teoria de conjuntos (álgebra relacional) atrelado a ideia de que não é relevante ao usuário saber onde os dados estão ou como eles se encontram, representado por uma coleção de tabelas (entidade/relação) é um conjunto de linhas (tuplas) uma lista de valores de atributos.</p><p>Considerando este contexto, avalie as seguintes asserções e a relação proposta entre elas:</p><p>I.Em um banco de dados relacional, o atributo tem a mesma funcionalidade que a entidade,</br>\r\n<center>PORQUE</center></br>II.é responsável por representar o objeto real na sua totalidade.</p><p>A respeito dessas asserções, assinale a opção correta.</p>', 'As asserções I e II são proposições verdadeiras, e a II é uma justificativa da I.', 'As asserções I e II são proposições verdadeiras, mas a II não é uma justificativa da I.', 'A asserção I é uma proposição verdadeira, e a II é uma proposição falsa.', 'A asserção I é uma proposição falsa, e a II é uma proposição verdadeira.', 'As asserções I e II são proposições falsas.', 'E', 2),
(29, '1', 'adg', 'Os bancos de dados podem ser simples ou extremamente complexos. O analista de sistemas deverá propor soluções, levando em consideração o volume de informações que deverá ser armazenado.</p><p>Marque a alternativa que corresponde ao conceito de banco de dados.', 'Podemos afirmar que banco de dados representam um conjunto de dados ou informações relacionadas entre si.', 'Podemos afirmar que banco de dados são um conjunto de instancias não  relacionadas entre si.', 'Conforme HEUSER (2009), um banco de dados é um conjunto de sistemas integrados que atendem a um conjunto maior de sistemas.', 'Um banco de dados pode ser considerado um conjunto de sistemas que se relacionam entre si e configuram um sistema maior.', 'Um banco de dados pode ser considerado um conjunto de objetos em um programa que se relacionam entre si.', 'A', 2),
(30, '1', 'adg', 'Quando no referenciamos ao termo aplicação, estamos mencionando os softwares que estarão se beneficiando dos dados armazenados em um banco de dados, por exemplo, como citado anteriormente, o sistema do setor financeiro de uma faculdade utiliza as informações armazenadas no banco de dados do sistema de controle acadêmico da secretaria da faculdade, ou seja, em poucas palavras podemos dizer que existe um banco de dados único e centralizado.</p><p>Marque a alternativa, que corresponde à forma de acesso ao banco de dados pelas aplicações.', 'O acesso ao banco de dado por diversas aplicações nem sempre necessita de regras específicas para garantir a segurança das informações inseridas.', 'A segurança das informações em um banco de dados não precisam passar por regras e nem garantir a integridade destas regras.', 'O acesso ao banco de dados por diversas aplicações necessitam de regras específicas para garantir tanto a segurança quanto a integridade das informações inseridas.', 'O acesso ao banco de dados pode ser feito por qualquer aplicação já que este acesso é liberado e livre de regras e integridade.', 'Os bancos de dados possuem regras liberadas de acesso aos seus dados.', 'C', 2),
(31, '1', 'adg', 'O objetivo geral de um banco de dados é centralizar as informações em determinado computador (servidor ou servidores), permitindo o compartilhamento dos dados entre os mais diversos sistemas e também que as relações entre as tabelas do banco  e registros sejam preservados.</p><p>O conceito, que determina que as relações entre tabelas devem ser preservadas, quando registros são atualizados ou excluídos, denomina-se', 'integridade de domínio.', 'integridade de entidade.', 'controle de acesso.', 'integridade referencial.', 'controle de inferência.', 'D', 2),
(32, '1', 'adg', 'A modelagem de dados tem por objetivo principal representar o ambiente observado, documentando e normalizando este ambiente, fornecendo processos de validação, observando processos de relacionamentos entre objetos.Nisto é importante destacar que os relacionamentos entre tabelas e objetos são conceitos fundamentais em um banco de dados e que devem ser preservadas em um banco de dados relacional.</p><p>Marque a alternativa onde o conceito, que determina que as relações entre tabelas devam ser preservadas, quando registros são atualizados ou excluídos.', 'Controle de Inferência.', 'Controle de acesso.', 'Integridade de entidade.', 'Integridade Referencial.', 'Integridade de domínio.', 'D', 2),
(33, '2', 'aap', 'No modelo conceitual é desenvolvido e identificado as principais entidades de negócios e de sistema de alto nível e os respectivos relacionamentos, que definem o escopo do problema a ser tratado pelo sistema.</p><p>Com relação à modelagem conceitual de dados assinale a opção correta.', 'Entidades fracas são representadas por um retângulo de borda simples e existem independentemente das entidades a elas relacionadas.', 'O modelo entidade relacionamento, semelhante à abordagem orientada a objetos de especialização e generalização, pode trabalhar com o conceito de supertipo e subtipos.', 'A notação de atributo multivalorado de uma entidade é representada por uma linha tracejada dupla.', 'No modelo DER, diferentemente do que ocorre no diagrama físico, não é necessário que os identificadores sejam notados no diagrama.', 'A participação opcional de uma entidade em um relacionamento é anotada com o número “0” na linha de associação com um atributo de multiplicidade.', 'B', 2),
(34, '2', 'aap', 'O sistema de banco de dados e sua arquitetura deve garantir uma visão totalmente abstrata do banco de dados para o usuário, ou seja, para o usuário do banco de dados pouco importa qual unidade de armazenamento está sendo usada para guardar seus dados, contanto que os mesmos estejam disponíveis no momento necessário.</p><p>As três visões da arquitetura básica de um SGBD, pela ordem, desde a mais próxima do usuário até a mais distante, são:', 'externa, conceitual e interna.', 'externa, interna e conceitual.', 'conceitual, interna e externa.', 'conceitual, externa e interna.', 'interna, conceitual e externa.', 'A', 2),
(35, '2', 'aap', 'A maneira mais difundida de se modelar dados é através do diagrama de entidade e relacionamento, usado para identificar os elementos (entidades) do sistema, os vínculos entre esses elementos (relacionamentos), e quantificadores que representam as regras para expressar o comportamento desses vínculos entre os elementos (cardinalidade).</p><p>Considerando a modelagem de dados, analise o seguinte script SQL para a criação das tabelas T1 e T2:<?p><p>É correto concluir que as tabelas T1 e T2 têm entre si:', 'um relacionamento 1:n.', 'um relacionamento n:m.', 'um relacionamento n:1.', 'um relacionamento 1:1.', 'qualquer tipo de relacionamento, dependendo da instância de cada uma.', 'D', 2),
(36, '2', 'aap', 'Em banco de dados a Modelagem relacional tem o conceito principal proveniente da teoria de conjuntos (álgebra relacional) atrelado a ideia de que não é relevante ao usuário saber onde os dados estão ou como eles se encontram, representado por uma coleção de tabelas (entidade/relação) é um conjunto de linhas (tuplas) uma lista de valores de atributos.</p><p>Em relação aos conceitos de bancos de dados e da modelagem relacional, é correto afirmar que:', 'Em uma generalização/especialização parcial, para cada ocorrência da entidade genérica, existe sempre uma ocorrência em uma das entidades especializadas.', 'O conjunto de valores que um atributo pode assumir é o domínio do atributo.', 'Um atributo pode possuir cardinalidade de relacionamentos.', 'Um relacionamento não pode possuir cardinalidade.', 'Um atributo não pode possuir cardinalidade.', 'D', 2),
(37, '2', 'adg', 'A modelagem de dados, de acordo com Coronel e Rob (2011, p.31), é um processo iterativo e progressivo, começando com uma compreensão simples do domínio do problema e, conforme essa compreensão se desenvolve, o nível de detalhes do modelo também se amplia.</p><p>O modelo de dados de mais alto nível, que serve para representar a estrutura dos dados de forma independente de um SGBD, com a principal preocupação de mapear as entidades e principais atributos que farão parte do modelo, é caracterizado como:', 'Modelo de Dados Relacional.', 'Modelo de Dados Conceitual.', 'Modelo Orientado a Objetos.', 'Modelo de Dados Físico.', 'Modelo de Dados Lógico.', 'B', 2),
(38, '2', 'adg', 'Os objetivos de um sistema de banco de dados são o de isolar o usuário dos detalhes internos do banco de dados (promover a abstração de dados) e promover a independência dos dados em relação às aplicações, ou seja, tornar independente da aplicação, a estratégia de acesso e a forma de armazenamento.</p><p>A abstração de um banco de dados pode acontecer em três níveis: visão do usuário; conceitual; e físico. Com relação a esta abstração avalie as alternativas:</p><p>I.   O nível de visão do usuário compreende as partes do banco de dados que o usuário tem acesso.<br>II.  O nível conceitual define quais os dados que estão armazenados sem preocupar-se com o relacionamento entre eles.<br>III. O nível físico define efetivamente de que maneira os dados estão armazenados.<br>IV. No nível conceitual podemos ter vários níveis de visão do usuário.<br>V.  Não importa qual unidade de armazenamento é usada para guardar os dados.</p><p>Agora, marque a alternativa CORRETA:', 'Apenas as afirmativas I e II estão corretas.', 'Apenas as afirmativas II e III estão corretas.', 'Apenas as afirmativas I, II e V estão corretas.', 'Apenas as afirmativas I, III, IV e V estão corretas.', 'Apenas as afirmativas I, II, III, IV e V estão corretas.', 'D', 2),
(39, '2', 'adg', 'Um modelo de banco de dados mostra a estrutura lógica de um banco de dados, incluindo as relações e restrições que determinam como os dados podem ser armazenados e acessados. Modelos de banco de dados individuais são projetados com base nas regras e nos conceitos do modelo de dados mais abrangente que os designers adotam.</p><p>O modelo de dados abstrato que descreve a estrutura de um banco de dados de forma independente de um SGBD chama-se modelo:', 'Lógico.', 'Funcional.', 'Algorítmico.', 'Físico.', 'Conceitual.', 'E', 2),
(40, '2', 'adg', 'A modelagem de banco dados é um passo importante para o desenvolvimento de qualquer sistema de informações, pois neste momento, através de uma especificação do seu cliente, será possível identificar todos os elementos importantes da solução que será implementada.</p><p>Marque a alternativa que representa o modelo criado em banco de dados, na fase conceitual com o objetivo de representar a semântica, associada aos requisitos do mini mundo.', 'Modelo Entidade Relacionamento.', 'Modelo Relacional.', 'Modelo de Classes.', 'Modelo de Casos de Uso.', 'Modelo Conceitual.', 'A', 2),
(41, '3', 'aap', 'Um banco de dados relacional é um mecanismo de armazenamento que permite a persistência de dados e opcionalmente implementar funcionalidades.</p><p>Sobre uma tabela de um banco de dados relacional, é correto afirmar que:', 'tem pelo menos duas chaves primárias.', 'sua chave primária deve ser do tipo literal.', 'pode conter somente um atributo do tipo booleano.', 'deve ter, no mínimo, um atributo do tipo numérico.', 'sua chave primária pode ser composta por mais de um atributo.', 'E', 2),
(42, '3', 'aap', 'Um Sistema Gerenciador de Banco de Dados Relacional (SGBDR) é um software que controla o armazenamento, recuperação, exclusão, segurança e integridade dos dados em um banco de dados. Um banco de dados relacional armazena dados em tabelas. Tabelas são organizadas em colunas, e cada coluna armazena um tipo de dados (inteiro, números reais, strings de caracteres, data, etc.).</p><p>Fonte: Bancos de Dados Relacionais. Disponível em:  <https://www.devmedia.com.br/bancos-de-dados-relacionais/20401>. Acesso em: 01 de Julho de 2018.</p><p>Analise as tabelas de banco de dados seguintes.</p><p>Quanto à cardinalidade das tabelas apresentadas, assinale a alternativa correta.', 'M:N.', '1:M.', '1:N.', '1:1.', 'N:N.', 'D', 2),
(43, '3', 'aap', 'Um diagrama entidade-relacionamento (ER) é um tipo de fluxograma que ilustra como “entidades”, p. ex., pessoas, objetos ou conceitos, se relacionam entre si dentro de um sistema. Diagramas ER são mais utilizados para projetar ou depurar bancos de dados relacionais nas áreas de engenharia de software, sistemas de informações empresariais, educação e pesquisa.</p><p>Fonte: O que é um diagrama entidade-relacionamento. Disponível em:  <https://www.lucidchart.com/pages/pt/o-que-e-diagrama-entidade-relacionamento>. Acesso em: 15 de Julho de 2018.</p><p>Observe o diagrama ER apresentado a seguir.\r\nConsidere as seguintes afirmativas sobre esse diagrama.</p><img><p>I. O relacionamento entre as entidades E2 e E3 é um relacionamento identificador.<br>II. O atributo A1 de E3 não pode admitir valores nulos na implementação.<br>III. Na declaração da chave estrangeira correspondente ao relacionamento entre E2 e E3, a opção on delete set null é uma decisão correta.<br>IV. A combinação dos atributos A1 e B3 deve formar um identificador para E3.<br>V. Na combinação dos atributos A1, A2 e B3 deve formar um identificador para E3.</p><p>Analisando o enunciado, marque a alternativa correta.', 'Apenas a afirmativa II é verdadeira.', 'Apenas a afirmativa  I é verdadeira.', 'Apenas as afirmativas I e IV são verdadeiras.', 'Apenas as afirmativas II e III são verdadeiras.', 'As afirmativas I, II, III,IV e V são verdadeiras.', 'B', 2),
(44, '3', 'aap', 'A finalidade da UML é proporcionar uma padronização nos projetos de sistemas, abrangendo aspectos conceituais, como regras de negócios e artefatos concretos como as classes, escritas em linguagens de programação, esquemas de banco de dados e componentes de software reutilizáveis. A Linguagem UML, conforme Fowler (2004), é composta de diversos diagramas.</p><p>Considerando os diagramas da UML, avalie as afirmativas a seguir:</p><p>I. Diagrama de Classes: é o diagrama mais usado da Linguagem UML pois pode representar um conjunto de classes e seus relacionamentos.<br>II. Diagrama de Sequência: determina o fluxo de tarefas que podem ser executadas pelo software ou por um ator.<br>III. Diagrama de Objetos: demostra como na realidade as informações do objeto podem ficar armazenas na classe.<br>IV. Diagrama de Caso de Uso: é um complemento do diagrama de classes, utilizado principalmente na fase de especificação dos requisitos do sistema pois demonstra os usuários e funcionalidades do software.<br>V. Diagrama de Atividades: demostra uma visão ou perspectiva norteada por tempo, da colaboração entre os objetos, principalmente com a ordem temporal em que as mensagens são trocadas.</p><p>Considerando o contexto apresentado, assinale a alternativa correta.', 'Apenas as afirmativas I e III estão corretas.', 'Apenas as afirmativas II e III estão corretas.', 'Apenas as afirmativas I, III e IV estão corretas.', 'Apenas as afirmativas I, II, III e IV estão corretas.', 'Apenas as afirmativas I, II, III e V estão corretas.', 'C', 2),
(45, '3', 'adg', 'O Modelo Entidade Relacionamento (também chamado Modelo ER, ou simplesmente MER), como o nome sugere, é um modelo conceitual utilizado na Engenharia de Software para descrever os objetos (entidades) envolvidos em um domínio de negócios, com suas características (atributos) e como elas se relacionam entre si (relacionamentos).</p><p>Ao estudar a notação do Modelo Entidade Relacionamento (MER) verifica-se que existem somente três tipos de relacionamento que são:', 'Um para um (1:1) - um para dois (1:2) - um para três (1:3).', 'Um para infinito (1:8) - infinito para um (8:1) - infinito para infinito (8:8).', 'Um para um (1:1) - um para muitos (1:N) - muitos para um (N:1).', 'Um para um (1:1) - um para muitos (1:N) - muitos para muitos (N:N).', 'Primeira forma normal (1FN) - segunda forma normal (2FN) - terceira forma normal (3FN).', 'D', 2),
(46, '3', 'adg', 'Alberto está concorrendo para uma vaga de analista de banco de dados em uma empresa conceituada do setor industrial. Para conseguir a vaga, teve que analisar e responder a seguinte situação:</p><p>Em um modelo de entidade e relacionamento, consideremos <b>X</b> uma entidade e <b>Y</b> um auto relacionamento de <b>X</b>. Do ponto de vista semântico, <b>X</b> é um conjunto, e <b>Y</b>, um conjunto de pares ordenados, cujos elementos pertencem a <b>X</b>. Se <b>X</b> representa um conjunto da população de uma determinada cidade onde a poligamia é ilegal e <b>Y</b> representa a relação casamento entre a população desta cidade:</p><p>Qual seria o tipo geral de relacionamento em que Y seria enquadrado? ', 'Um para zero.', 'Muitos para um.', 'Muitos para muitos.', 'Um para muitos.', 'Um para um.', 'E', 2),
(47, '3', 'adg', 'Observe o relacionamento entre as entidades “Pedido” e “Itens do Pedido” e as premissas relacionadas a seguir:</p><p>1. A existência da entidade Itens do Pedido está condicionada à existência da entidade Pedida.<br>2.Na entidade Pedido, Número do Pedido identifica um pedido.<br>3.Na entidade Itens do Pedido, Descrição do Item é um campo texto com até 255 caracteres.<br>4.Na entidade Itens do Pedido, para cada Número do Pedido, Código do Item identifica um único item do pedido correspondente.</p><img><p>Assinale a alternativa correta quanto a analise da figura.', 'Pedido é uma entidade Fraca.', 'Código do Item é uma chave estrangeira.', 'Descrição do Item é um atributo multivalorado.', 'O relacionamento entre as entidades “Pedido” e “ Itens do Pedido” é chamado de autor-relacionamento.', 'A chave primária de Itens do Pedido é composta pelos atributos Número do Pedido e Código do Item.', 'E', 2),
(48, '3', 'adg', 'A figura 01 ilustra um diagrama comumente utilizado no desenvolvimento de sistemas por meio da metodologia UML. Esse tipo de diagrama é muito utilizado principalmente na fase de especificação dos requisitos do sistema. Na Figura é demonstrado os possíveis usuários e as funcionalidades do software.</p><img><p>Assinale a alternativa que representa o diagrama UML representado na figura.', 'Diagrama de Fluxo de Processos.', 'Diagrama de Casos de Uso.', 'Diagrama de Atividades.', 'Diagrama de Classes.', 'Diagrama de Interação.', 'B', 2);

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `alunos`
--
ALTER TABLE `alunos`
  ADD PRIMARY KEY (`idAluno`);

--
-- Índices para tabela `disciplinas`
--
ALTER TABLE `disciplinas`
  ADD PRIMARY KEY (`idDisciplina`);

--
-- Índices para tabela `perguntas`
--
ALTER TABLE `perguntas`
  ADD PRIMARY KEY (`idPergunta`),
  ADD KEY `idDisciplina` (`idDisciplina`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `alunos`
--
ALTER TABLE `alunos`
  MODIFY `idAluno` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de tabela `disciplinas`
--
ALTER TABLE `disciplinas`
  MODIFY `idDisciplina` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT de tabela `perguntas`
--
ALTER TABLE `perguntas`
  MODIFY `idPergunta` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;

--
-- Restrições para despejos de tabelas
--

--
-- Limitadores para a tabela `perguntas`
--
ALTER TABLE `perguntas`
  ADD CONSTRAINT `perguntas_ibfk_1` FOREIGN KEY (`idDisciplina`) REFERENCES `disciplinas` (`idDisciplina`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
